<a href="https://colab.research.google.com/github/ssingh121/Python-Lab/blob/main/LAB3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# Create an array of shape (2, 3, 4) of zeros
zeros_array = np.zeros((2, 1, 1))
print("Zeros Array:")
print(zeros_array)

Zeros Array:
[[[0.]]

 [[0.]]]


In [ ]:
# Create an array of shape (2, 3, 4) of ones
ones_array = np.ones((2, 3, 4))
print("Ones Array:")
print(ones_array)

Ones Array:
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [ ]:
# Create an array with values 0 to 999 using the "np.arange" function
arr_0_to_999 = np.arange(1000)
print("Array from 0 to 999:")
print(arr_0_to_999)

Array from 0 to 999:
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 2

In [ ]:
# Create an array from the list [2, 3.2, 5.5, -6.4, -2.2, 2.4] and assign it to the variable "a"
a = np.array([2, 3.2, 5.5, -6.4, -2.2, 2.4])
print("Array 'a':", a)
print("a[1] =", a[1])  # Print a[1]
print("a[1:4] =", a[1:4])  # Print a[1:4]

Array 'a': [ 2.   3.2  5.5 -6.4 -2.2  2.4]
a[1] = 3.2
a[1:4] = [ 3.2  5.5 -6.4]


In [ ]:
# Create a 2-D array from the given list and assign it to the variable "a"
a = np.array([[2, 3.2, 5.5, -6, 4, -2.2, 2.4], [1, 22, 4, 0.1, 5, 3, -9], [3, 1, 2, 1, 21, 1.1, -2]])
print(a);

[[ 2.   3.2  5.5 -6.   4.  -2.2  2.4]
 [ 1.  22.   4.   0.1  5.   3.  -9. ]
 [ 3.   1.   2.   1.  21.   1.1 -2. ]]


In [ ]:
import numpy as np

# Create a 2-D array from the given list
a = np.array([[2, 3.2, 5.5, -64, -2.2, 2.4],
              [1, 22, 4, 0.1, 5.3, -9],
              [3, 1, 2, 1, 21, 1.1]])
print("\nArray 'a':\n", a)

# Extract the necessary slices and reshape to make the arrays compatible
slice_1 = a[1:4, 0:4]
slice_2 = a[1:, 2].reshape(-1, 1)  # Reshape to match the dimensions for broadcasting

# Perform element-wise multiplication
result = slice_1 * slice_2

# Check if slices are equal
print("Slices are equal:", np.array_equal(a[:, 3], result.flatten()))



Array 'a':
 [[  2.    3.2   5.5 -64.   -2.2   2.4]
 [  1.   22.    4.    0.1   5.3  -9. ]
 [  3.    1.    2.    1.   21.    1.1]]
Slices are equal: False


In [ ]:
# Create a 2-D array of shape (2, 4) containing two lists and assign it to the variable "arr"
arr = np.array([list(range(4)), list(range(10, 14))])
print("2-D Array 'arr':\n", arr)
print("Shape of arr:", arr.shape)  # Print shape of arr
print("Size of arr:", arr.size)  # Print size of arr
print("Maximum of arr:", np.max(arr))  # Print maximum of arr
print("Minimum of arr:", np.min(arr))  # Print minimum of arr

2-D Array 'arr':
 [[ 0  1  2  3]
 [10 11 12 13]]
Shape of arr: (2, 4)
Size of arr: 8
Maximum of arr: 13
Minimum of arr: 0


In [ ]:
# Continue using array "arr" as defined above
print("Reshaped arr to (2, 2, 2):\n", arr.reshape(2, 2, 2))  # Print re-shaped array to (2, 2, 2)
print("Transposed arr:\n", arr.T)  # Print transposed array
print("Flattened arr:", arr.flatten())  # Print flattened array
print("Array converted to floats:\n", arr.astype(float))  # Print array converted to floats

Reshaped arr to (2, 2, 2):
 [[[ 0  1]
  [ 2  3]]

 [[10 11]
  [12 13]]]
Transposed arr:
 [[ 0 10]
 [ 1 11]
 [ 2 12]
 [ 3 13]]
Flattened arr: [ 0  1  2  3 10 11 12 13]
Array converted to floats:
 [[ 0.  1.  2.  3.]
 [10. 11. 12. 13.]]


In [ ]:
# Create an array counting from 1 to 20 inclusive
counting_array = np.arange(1, 21)
print("Array counting from 1 to 20 inclusive:", counting_array)

Array counting from 1 to 20 inclusive: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
# Array of multiples of 3 greater than 0 and less than 30
multiples_of_3 = np.arange(3, 30, 3)
print("Array of multiples of 3:", multiples_of_3)

Array of multiples of 3: [ 3  6  9 12 15 18 21 24 27]


In [ ]:
# Array of 8 equally spaced floats x where 0 <= x <= 1
equally_spaced_floats = np.linspace(0, 1, 8)
print("Array of 8 equally spaced floats:", equally_spaced_floats)

Array of 8 equally spaced floats: [0.         0.14285714 0.28571429 0.42857143 0.57142857 0.71428571
 0.85714286 1.        ]


In [ ]:
# Use np.arange and reshape to create the array A
A = np.arange(1, 9).reshape(2, 4)
print("Array A:\n", A)

Array A:
 [[1 2 3 4]
 [5 6 7 8]]


In [ ]:
# Use np.array to create the array B
B = np.array([1, 2])
print("Array B:", B)

Array B: [1 2]


In [ ]:
import numpy as np

# Create array A using np.arange and reshape
A = np.arange(1, 9).reshape(2, 4)
print("Array A:\n", A)

# Create array B using np.array
B = np.array([1, 2])
print("Array B:", B)

# Use broadcasting to add B to A to create the final array A + B
final_array = A + B.reshape(-1, 1)  # Reshape B to (2, 1) to match the shape of A
print("A + B =", final_array)


Array A:
 [[1 2 3 4]
 [5 6 7 8]]
Array B: [1 2]
A + B = [[ 2  3  4  5]
 [ 7  8  9 10]]
